### ISSUE TITLE
TVM build failing saying kDLVulkan defined twice

### ISSUE THREAD

**Issue by pallabdatta** [dmlc/tvm#1710]
Hi @tqchen 

We are trying to build TVM fresh within a docker container by doing the following:

git clone https://github.com/dmlc/tvm.git

followed by the commands within tvm: 
git submodule update --init --recursive
git submodule update --recursive --remote

Then the build fails saying that the variable "kDLVulkan" has been defined twice.
I see some inconsistencies between an older version of DLPack and the recent ones.
The build was successful till very recently. Can you suggest what the fix might be? or help us fix it.
thanks a lot in advance,
pallab

root@09d777179a12:/workspace/tvm/build# cmake ../  -DUSE_CUDA:BOOL=ON  -DUSE_LLVM:BOOL=ON -DUSE_CUDA:BOOL=ON  -DUSE_GRAPH_RUNTIME:BOOL=ON  -DUSE_METAL:BOOL=OFF -DUSE_MSVC_MT:BOOL=OFF -DUSE_OPENCL:BOOL=OFF  
-DUSE_RPC:BOOL=ON
-- Build with RPC support...
-- Build with Graph runtime support...
-- Build with CUDA support
-- Link with dynamic LLVM library
-- Build with LLVM 5.0.0
-- Set TVM_LLVM_VERSION=50
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/tvm/build
root@09d777179a12:/workspace/tvm/build# make
[  0%] Building CXX object CMakeFiles/tvm.dir/src/api/api_arith.cc.o
In file included from /workspace/np-compiler/tvm/include/tvm/runtime/packed_func.h:17:0,
                 from /workspace/np-compiler/tvm/include/tvm/runtime/registry.h:30,
                 from /workspace/np-compiler/tvm/include/tvm/base.h:15,
                 from /workspace/np-compiler/tvm/include/tvm/expr.h:14,
                 from /workspace/np-compiler/tvm/src/api/api_arith.cc:6:
/workspace/tvm/include/tvm/runtime/c_runtime_api.h:65:15: error: redeclaration of \u2018kDLVulkan\u2019
   kDLVulkan = 7,
               ^
In file included from /workspace/tvm/include/tvm/runtime/c_runtime_api.h:50:0,
                 from /workspace/tvm/include/tvm/runtime/packed_func.h:17,
                 from /workspace/tvm/include/tvm/runtime/registry.h:30,
                 from /workspace/tvm/include/tvm/base.h:15,
                 from /workspace/tvm/include/tvm/expr.h:14,
                 from /workspace/tvm/src/api/api_arith.cc:6:
/workspace/tvm/dlpack/include/dlpack/dlpack.h:51:3: note: previous declaration \u2018DLDeviceType kDLVulkan\u2019
   kDLVulkan = 7,
   ^
CMakeFiles/tvm.dir/build.make:62: recipe for target 'CMakeFiles/tvm.dir/src/api/api_arith.cc.o' failed
make[2]: *** [CMakeFiles/tvm.dir/src/api/api_arith.cc.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/tvm.dir/all' failed
make[1]: *** [CMakeFiles/tvm.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tqchen** [comment]
Please use https://discuss.tvm.ai for installation questions, this was due to a recent update in dlpack(to contain kDLVulkan) and the master has not been updated to the latest dlpack version. Fix your dlpack version to be the same as the tvm repo should resolve the problem
