### ISSUE TITLE
bug in compile with cudnn-v5.1.5

### ISSUE THREAD

**Issue by solin319** [dmlc/tvm#578]
cuda : v8.0
cudnn : v5.1.5

I compile the source code with below config.
```
USE_CUDA = 1
CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
```

There is an error when execute 'make'.
```
src/contrib/cudnn/cudnn_utils.cc:17:57: error: ‘CUDNN_DATA_INT8’ was not declared in this scope
         if (dtype.bits == 8 && dtype.lanes == 1) return CUDNN_DATA_INT8;
                                                         ^
src/contrib/cudnn/cudnn_utils.cc:18:63: error: ‘CUDNN_DATA_INT32’ was not declared in this scope
         else if (dtype.bits == 32 && dtype.lanes == 1) return CUDNN_DATA_INT32;
                                                               ^
src/contrib/cudnn/cudnn_utils.cc:19:62: error: ‘CUDNN_DATA_INT8x4’ was not declared in this scope
         else if (dtype.bits == 8 && dtype.lanes == 4) return CUDNN_DATA_INT8x4;
                                                              ^
src/contrib/cudnn/cudnn_utils.cc: In static member function ‘static const void* tvm::contrib::CuDNNDataType::GetConst(cudnnDataType_t) [with int v = 0]’:
src/contrib/cudnn/cudnn_utils.cc:48:15: error: ‘CUDNN_DATA_INT8’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
               ^
src/contrib/cudnn/cudnn_utils.cc:48:42: error: ‘CUDNN_DATA_INT32’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
                                          ^
src/contrib/cudnn/cudnn_utils.cc:48:70: error: ‘CUDNN_DATA_INT8x4’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
                                                                      ^
src/contrib/cudnn/cudnn_utils.cc: In static member function ‘static const void* tvm::contrib::CuDNNDataType::GetConst(cudnnDataType_t) [with int v = 1]’:
src/contrib/cudnn/cudnn_utils.cc:65:15: error: ‘CUDNN_DATA_INT8’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
               ^
src/contrib/cudnn/cudnn_utils.cc:65:42: error: ‘CUDNN_DATA_INT32’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
                                          ^
src/contrib/cudnn/cudnn_utils.cc:65:70: error: ‘CUDNN_DATA_INT8x4’ was not declared in this scope
   if (type == CUDNN_DATA_INT8 || type == CUDNN_DATA_INT32 || type == CUDNN_DATA_INT8x4) {
```

This problem cause by cudnn-v5.1.5 doesn't include the define for CUDNN_DATA_INT8, CUDNN_DATA_INT32 ...

Does TVM only support cudnn-v7

**Comment by tqchen** [comment]
Yes, only cudnnv7 is supported, however, you do not have to build tvm with cudnn.
